
[[List]]
Name = '''movementtypes'''
0 = [
   '''face_down''',
   '''face_up''',
   '''face_left''',
   '''face_right''',
   '''face_down_fast''',
   '''face_up_fast''',
   '''face_left_fast''',
   '''face_right_fast''',
   '''walk_slowest_down''',
   '''walk_slowest_up''',
   '''walk_slowest_left''',
   '''walk_slowest_right''',
   '''walk_slow_down''',
   '''walk_slow_up''',
   '''walk_slow_left''',
   '''walk_slow_right''',
   '''walk_down''',
   '''walk_up''',
   '''walk_left''',
   '''walk_right''',
   '''jump_2_down''',
   '''jump_2_up''',
   '''jump_2_left''',
   '''jump_2_right''',
   '''delay_1''',
   '''delay_2''',
   '''delay_4''',
   '''delay_8''',
   '''delay_16''',
   '''walk_fast_down''',
   '''walk_fast_up''',
   '''walk_fast_left''',
   '''walk_fast_right''',
   '''walk_in_place_slow_down''',
   '''walk_in_place_slow_up''',
   '''walk_in_place_slow_left''',
   '''walk_in_place_slow_right''',
   '''walk_in_place_down''',
   '''walk_in_place_up''',
   '''walk_in_place_left''',
   '''walk_in_place_right''',
   '''walk_in_place_fast_down''',
   '''walk_in_place_fast_up''',
   '''walk_in_place_fast_left''',
   '''walk_in_place_fast_right''',
   '''walk_in_place_fastest_down''',
   '''walk_in_place_fastest_up''',
   '''walk_in_place_fastest_left''',
   '''walk_in_place_fastest_right''',
   '''face_down_slow''',
   '''face_up_slow''',
   '''face_left_slow''',
   '''face_right_slow''',
   '''walk_fastest_down''',
   '''walk_fastest_up''',
   '''walk_fastest_left''',
   '''walk_fastest_right''',
   '''slide_down''',
   '''slide_up''',
   '''slide_left''',
   '''slide_right''',
   '''player_run_down''',
   '''player_run_up''',
   '''player_run_left''',
   '''player_run_right''',
   '''player_run_down_slow''',
   '''player_run_up_slow''',
   '''player_run_left_slow''',
   '''player_run_right_slow''',
   '''step_45''',
   '''jump_down_run''',
   '''jump_up_run''',
   '''jump_left_run''',
   '''jump_right_run''',
   '''face_player''',
   '''face_away_player''',
   '''lock_facing_direction''',
   '''unlock_facing_direction''',
   '''jump_down''',
   '''jump_up''',
   '''jump_left''',
   '''jump_right''',
   '''jump_in_place_down''',
   '''jump_in_place_up''',
   '''jump_in_place_left''',
   '''jump_in_place_right''',
   '''jump_in_place_down_up''',
   '''jump_in_place_up_down''',
   '''jump_in_place_left_right''',
   '''jump_in_place_right_left''',
   '''face_original_direction''',
   '''nurse_joy_bow''',
   '''enable_jump_landing_ground_effect''',
   '''disable_jump_landing_ground_effect''',
   '''disable_anim''',
   '''restore_anim''',
   '''set_invisible''',
   '''set_visible''',
   '''emote_exclamation_mark''',
   '''emote_question_mark''',
   '''emote_x''',
   '''emote_double_exclamation_mark''',
   '''emote_smile''',
   '''reveal_trainer''',
   '''rock_smash_break''',
   '''cut_tree''',
]
