[[NamedAnchors]]
Name = '''GameTitle'''
Address = 0x0000A0
Format = '''`asc`12'''

[[NamedAnchors]]
Name = '''GameCode'''
Address = 0x0000AC
Format = '''`asc`4'''

[[NamedAnchors]]
Name = '''MakerCode'''
Address = 0x0000B0
Format = '''`asc`2'''

[[List]]
Name = '''moveeffects'''
0 = [
   '''None''',
   '''SleepPrimary''',
   '''Poison''',
   '''HealHalf''',
   '''Burn''',
   '''Freeze''',
   '''Paralyze''',
   '''Suicide''',
   '''HealHalfIfOpponentSleeping''',
   '''RepeatFoeMove''',
   '''RaiseAttackPrimary''',
   '''RaiseDefensePrimary''',
   '''???RaiseSpeedPrimary???''',
   '''RaiseAttackSpAttackPrimary''',
   '''unknown1''',
   '''???RaiseAccuracyPrimary???''',
   '''RaiseEvasivenessPrimary''',
   '''NeverMiss''',
   '''LowerAttackPrimary''',
   '''LowerDefensePrimary''',
   '''LowerSpeedPrimary''',
   '''???LowerAttackSpAttackPrimary???''',
   '''unknown2''',
   '''LowerAccuracyPrimary''',
   '''LowerEvasionPrimary''',
   '''RemoveStateChanges''',
   '''Bide''',
   '''2to3turnsThenConfused''',
   '''OpponentSwitch''',
   '''2to5hits''',
   '''ChangeTypeToFriendlyMove''',
   '''Flinch''',
   '''Recover''',
   '''BadPoisonPrimary''',
   '''Money''',
   '''RaiseSpDef2Wall''',
   '''ParalyzeBurnFreeze''',
   '''Rest''',
   '''OHKO''',
   '''2turnHighCrit''',
   '''HalfDamage''',
   '''20Damage''',
   '''2to5turnTrap''',
   '''HighCrit''',
   '''2hits''',
   '''MissHurtSelf''',
   '''PreventStatReduction''',
   '''RaiseCriticalRate''',
   '''25Recoil''',
   '''ConfusionPrimary''',
   '''RaiseAttack2Primary''',
   '''RaiseDefense2Primary''',
   '''RaiseSpeed2Primary''',
   '''RaiseSpAtk2Primary''',
   '''RaiseSpDef2Primary''',
   '''???RaiseAccuracy2Primary???''',
   '''???RaiseEvasiveness2Primary???''',
   '''Transform''',
   '''LowerAttack2Primary''',
   '''LowerDefense2Primary''',
   '''LowerSpeed2Primary''',
   '''???LowerSpAtk2Primary???''',
   '''LowerSpDef2Primary''',
   '''???''',
   '''????''',
   '''RaiseDefense2Wall''',
   '''PoisonPrimary''',
   '''ParalyzePrimary''',
   '''LowerAttack''',
   '''LowerDefense''',
   '''LowerSpeed''',
   '''LowerSpAtk''',
   '''LowerSpDef''',
   '''LowerAccuracy''',
   '''?????''',
   '''2turnHighCritFlinch''',
   '''Confusion''',
   '''2hitsPoison''',
   '''NeverMiss(VitalThrow)''',
   '''Substitute''',
   '''SkipNextTurn''',
   '''StrongerForLessHealth''',
   '''Mimic''',
   '''RandomMove''',
   '''SeedOpponent''',
   '''Splash''',
   '''Disable''',
   '''DamageBasedOnLevel''',
   '''DamageRandom''',
   '''DoublePhysicalDamage''',
   '''OpponentRepeatMoveFor2to6turns''',
   '''PainSplit''',
   '''WhileSleepingFlinch''',
   '''ChangeTypeToResistPreviousHit''',
   '''NextAttackHits''',
   '''Sketch''',
   '''??????''',
   '''SleepTalk''',
   '''DestinyBond''',
   '''StrengthDependsOnHealth''',
   '''ReducePP''',
   '''FalseSwipe''',
   '''HealPartyStatus''',
   '''NormalPlusPriority''',
   '''3turnTripleHit''',
   '''StealItem''',
   '''NoSwitch''',
   '''Nightmare''',
   '''RaiseEvasivenessAndBecomeSmaller''',
   '''Curse''',
   '''??''',
   '''EvadeNextAttack''',
   '''Spikes''',
   '''FoeCannnotRaiseEvasion''',
   '''PerishSong''',
   '''Sandstorm''',
   '''Endure''',
   '''5turnsUntilMiss''',
   '''ConfuseAndRaiseAttack2''',
   '''GetStrongerEachHit''',
   '''Attract''',
   '''StrongerWithFriendship''',
   '''Present''',
   '''WeakerWithFriendship''',
   '''PreventStatus5Turns''',
   '''BurnRaiseSpeed''',
   '''Magnitude''',
   '''BatonPass''',
   '''DoublePowerIfOpponentSwitching''',
   '''RemoveBindSeedSpikes''',
   '''20Damage''',
   '''???????''',
   '''MorningSun''',
   '''Synthesis''',
   '''Moonlight''',
   '''HiddenPower''',
   '''Rain5turns''',
   '''Sun5turns''',
   '''RaiseDefense''',
   '''RaiseAttack''',
   '''RaiseAllStats''',
   '''????????''',
   '''HalfHealthToRaiseAttack6''',
   '''CopyFoeStatChangesPrimary''',
   '''DoubleSpecialDamage''',
   '''RaiseDefenseThenAttackTurn2''',
   '''FlinchAndDoubleDamageToFly''',
   '''DoubleDamageToDig''',
   '''DamageIn2Turns''',
   '''DoubleDamageToFly''',
   '''FlinchAndDoubleDamageToMinimize''',
   '''ChargeFirstTurn''',
   '''ParalyzeAndIncreaseAccuracyInRain''',
   '''Escape''',
   '''DamageBasedOnPartySize''',
   '''2turn''',
   '''RaiseDefenseAndImproveRollingMoves''',
   '''RecoverOrFriend''',
   '''OnlyWorksOnce''',
   '''2to5turnsNoSleep''',
   '''Stockpile''',
   '''Spit Up''',
   '''Swallow''',
   '''?????????''',
   '''Hail5turns''',
   '''Torment''',
   '''ConfuseAndRaiseSpAtk2''',
   '''BurnPrimary''',
   '''SuicideLowerAtkSpAtk2''',
   '''DoubleDamageIfStatus''',
   '''SelfFlinchIfHit''',
   '''DoubleDamageToParalyzeAndHealParalyze''',
   '''ForceFoesAttackMe''',
   '''NaturePower''',
   '''BoostNextElectricMove''',
   '''Taunt''',
   '''BoostAllyPower''',
   '''TradeHeldItems''',
   '''CopyAbility''',
   '''HealHalfNextTurn''',
   '''UseAllyMove''',
   '''Ingrain''',
   '''LowerSelfAtkDef''',
   '''ReflectStatusMoves''',
   '''Recycle''',
   '''DoubleDamageIfHitThisTurn''',
   '''BreakWall''',
   '''Yawn''',
   '''KnockOff''',
   '''Endeavor''',
   '''DamageBasedOnHighRemainingHealth''',
   '''SkillSwap''',
   '''Imprison''',
   '''HealSelfStatus''',
   '''Grudge''',
   '''Snatch''',
   '''DamageBasedOnWeight''',
   '''SecondEffectBasedOnTerrain''',
   '''33Recoil''',
   '''ConfuseAllPokemon''',
   '''HighCritBurn''',
   '''MudSport''',
   '''BadPoison''',
   '''WeatherBall''',
   '''LowerSpAtk2Self''',
   '''LowerAttackDefensePrimary''',
   '''RaiseDefenseSpDef''',
   '''CanDamageFly''',
   '''RaiseAttackDefensePrimary''',
   '''HighCritPoison''',
   '''WaterSport''',
   '''RaiseSpAtkSpDefPrimary''',
   '''RaiseAttackSpeedPrimary''',
   '''ChangetypeFromTerrain''',
]

[[List]]
Name = '''moveinfo'''
0 = [
   '''Makes Contact''',
   '''Affected by Protect''',
   '''Affected by Magic Coat''',
   '''Affected by Snatch''',
   '''Affected by Mirror Move''',
   '''Affected by King's Rock''',
]

[[List]]
Name = '''movetarget'''
0 = [
   '''RecentAttacker''',
   '''Unused''',
   '''Random''',
   '''Both''',
   '''Self''',
   '''Everyone''',
   '''Hazard''',
]

[[List]]
Name = '''trainerStructType'''
0 = [
    '''Normal''',
    '''Moves''',
    '''Items''',
    '''Both''',
]

[[List]]
Name = '''decorpermissions'''
0 = [
   '''Normal''',
   '''Put On Floor''',
   '''Object''',
   '''Place On Wall''',
   '''Doll or Cushion''',
]

[[List]]
Name = '''decorcategory'''
0 = [
   '''Desk''',
   '''Chair''',
   '''Plant''',
   '''Unique''',
   '''Mat''',
   '''Poster''',
   '''Doll''',
   '''Cushion''',
]

[[List]]
Name = '''decorshape'''
0 = [
   '''1x1''',
   '''unused''',
   '''unused''',
   '''1x1t''',
   '''2x2p''',
   '''1x1p''',
   '''unused''',
   '''3x1''',
   '''2x2''',
   '''2x1''',
]

[[List]]
Name = '''evolutionmethods'''
0 = [
   '''None''',
   '''Happiness''',
   '''Happy Day''',
   '''Happy Night''',
   '''Level''',
   '''Trade''',
   '''Trade Item''',
   '''Stone''',
   '''Level High Attack''',
   '''Level Attack matches Defense''',
   '''Level High Defense''',
   '''Level Odd Personality''',
   '''Level Even Personality''',
   '''Level And New Pokemon''',
   '''Level But New Pokemon''',
   '''Beauty''',
]

[[List]]
Name = '''evbits'''
0 = [
   '''+1 HP''',
   '''+2 HP''',
   '''+1 Attack''',
   '''+2 Attack''',
   '''+1 Defense''',
   '''+2 Defense''',
   '''+1 Speed''',
   '''+2 Speed''',
   '''+1 Sp Attack''',
   '''+2 Sp Attack''',
   '''+1 Sp Defense''',
   '''+2 Sp Defense''',
]

[[List]]
Name = '''traineraibits'''
0 = [
   '''CheckBadMove''',
   '''TryToFaint''',
   '''CheckViability''',
   '''SetupFirstTurn''',
   '''Risky''',
   '''PreferStrongestMove''',
   '''PreferBatonPass''',
   '''DoubleBattle''',
   '''HPAware''',
   '''Unknown''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Roaming''',
   '''Safari''',
   '''FirstBattle''',
]

[[List]]
Name = '''script_compare'''
0 = [
    '''<''',
    '''=''',
    '''>''',
    '''<=''',
    '''>=''',
    '''!=''',
]

